name: Build

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to NPM
        run: yarn publish --access=public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
